name: CI

on:
  push:
    branches: [ master, '6.0' ]
  pull_request:
    branches: [ master, '6.0' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Build
        run: |
          psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
          psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
          psql -c 'CREATE EXTENSION ltree' -U postgres  -h 127.0.0.1 pomm_test
          psql -c 'CREATE TABLE config (name character varying(25) PRIMARY KEY, value character varying(25))' -U postgres -h 127.0.0.1 pomm_test
          psql -c "INSERT INTO config VALUES ('test', 'value')" -U postgres -h 127.0.0.1 pomm_test
          psql -c 'CREATE DATABASE pomm_test_2' -U postgres -h 127.0.0.1 postgres
          psql -c 'CREATE TABLE config (name character varying(25) PRIMARY KEY, value character varying(25))' -U postgres -h 127.0.0.1 pomm_test_2
          psql -c "INSERT INTO config VALUES ('test', 'value_db2')" -U postgres -h 127.0.0.1 pomm_test_2
          composer update -n --prefer-dist --prefer-stable
          ln -fs ./parameters.yml.dist ./tests/app/config/parameters.yml
          cd tests/
          composer update -n --prefer-dist --prefer-stable
          rm -rf vendor/conserto/pomm-bundle
          ln -s ../../../ vendor/conserto/pomm-bundle

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon
          memory_limit: 256M
          path: ''
          php_version: 8.4

      - name: PHPCS Analysis
        run: |
          ./vendor/bin/phpcs --standard=psr12 --runtime-set ignore_warnings_on_exit true --report=summary ./sources

      - name: Run tests
        run: |
          cd tests/
          ./app/console pomm:generate:schema-all -d 'src/'  -a 'AppBundle\Model' my_db1
          ./bin/phpunit -c tests/phpunit.xml tests/PhpUnit/
